// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityframeworkcore_one_to_one_relationship_example_project.Data;

#nullable disable

namespace entityframeworkcore_one_to_one_relationship_fluent_api_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122105817_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("entityframeworkcore_one_to_one_relationship_example_project.Models.CarCompany", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CarCompanies");
                });

            modelBuilder.Entity("entityframeworkcore_one_to_one_relationship_example_project.Models.CarModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CarCompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CarCompanyID")
                        .IsUnique();

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("entityframeworkcore_one_to_one_relationship_example_project.Models.CarModel", b =>
                {
                    b.HasOne("entityframeworkcore_one_to_one_relationship_example_project.Models.CarCompany", "CarCompany")
                        .WithOne("CarModel")
                        .HasForeignKey("entityframeworkcore_one_to_one_relationship_example_project.Models.CarModel", "CarCompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarCompany");
                });

            modelBuilder.Entity("entityframeworkcore_one_to_one_relationship_example_project.Models.CarCompany", b =>
                {
                    b.Navigation("CarModel");
                });
#pragma warning restore 612, 618
        }
    }
}
