@entityframeworkcore_one_to_one_relationship_fluent_api_project_HostAddress = http://localhost:5111

GET {{entityframeworkcore_one_to_one_relationship_fluent_api_project_HostAddress}}/weatherforecast/
Accept: application/json

###
